### ISSUE TITLE
trie file missing. 

### ISSUE THREAD

**Issue by Tortoise17** [ynop/deepspeech-german#10]
Dear. 

I want to ask that I am facing the issue. 
/deepspeech-german/data/trie: The file pointed to by --lm_trie_path must exist and be readable.

when I run the command ./run_training.

Can you guide me how to make trie file from Deepspeech?

I tried several ways and failed. 
Please help.

**Comment by ynop** [comment]
You can find the command here:
https://github.com/ynop/deepspeech-german/blob/master/run_all.sh

```
$deepspeech/native_client/generate_trie data/alphabet.txt $exp_path/lm.binary $exp_path/cleaned_vocab.txt $exp_path/trie
```

$deepspeech is the root directory of the DeepSpeech repository.

But I'am not sure if this still works, haven't run it in a while.

**Comment by Tortoise17** [comment]
Dear .. 
I am facing issues with this step 
$deepspeech/native_client/generate_trie data/alphabet.txt $exp_path/lm.binary $exp_path/cleaned_vocab.txt $exp_path/trie

specifically 
deepspeech/native_client/generate_trie

**Comment by ynop** [comment]
issues? A bit more info ...
Can't give you a step-by-step guide.

**Comment by Tortoise17** [comment]
I am really impressed by your efforts. I am interested in this work. 

In easy words. I am trying to train a model from scratch. I downloaded the data and followed your all steps. But, I cannot create trie file. 
If I use the command then .. 

$./run_all.sh
Traceback (most recent call last):
  File "./prepare_data.py", line 67, in <module>
    swc_corpus = audiomate.Corpus.load(swc_path, reader='kaldi')
  File "/home/anaconda3/envs/python/lib/python3.6/site-packages/audiomate/corpus/corpus.py", line 123, in load
    return reader.load(path)
  File "/home/anaconda3/envs/python/lib/python3.6/site-packages/audiomate/corpus/io/base.py", line 79, in load
    self.type(), ' '.join(missing_files), path))
OSError: Invalid data set of type kaldi: files wav.scp text not found at /home/deepspeech-german/data/SWC_2017_10
(python) [user@localhost deepspeech-german]$ 

while, I downloaded the data and prepared .. 
I prepared the data with step by step command. 

Now the failure is at the stage of generation of trie file.

**Comment by Tortoise17** [comment]
$./run_training
deepspeech-german/data: The file pointed to by --alphabet_config_path must exist and be readable.

**Comment by ynop** [comment]
That's just the preparation step, nothing to do with the trie.

But SWC Corpus is quite the pain.
This causes the ```OSError: Invalid data set of type kaldi: files wav.scp``` error.
You first need to convert it to the correct format, manually.
(See https://audiomate.readthedocs.io/en/latest/documentation/indirect_support.html)

**Comment by Tortoise17** [comment]
This i converted and the each folder has the .wav file in addition to .ogg file. 
here is the point maybe you understand, 

$DeepSpeech/native_client/generate_trie deepspeech-german/data/alphabet.txt deepspeech-german/data/lm.binary  deepspeech-german/data/clean_vocab.txt deepspeech-german/data/trie

bash: DeepSpeech/native_client/generate_trie: No such file or directory

**Comment by ynop** [comment]
You have to install the deepspeech nativeclient stuff, see the readme:
https://github.com/mozilla/DeepSpeech/tree/master/native_client

Then use the correct path to the generate_trie binary.

**Comment by Tortoise17** [comment]
Thank you so much. I got it .. My mistake.
