### ISSUE TITLE
common voice data preprocessing

### ISSUE THREAD

**Issue by Tortoise17** [ynop/deepspeech-german#12]
Hi. 

It seems that there is something issue with common voice dataset. When I try to use it for pre-processing, there is error like 

python prepare_data.py --cv data/clips data/clips
Traceback (most recent call last):
  File "prepare_data.py", line 88, in <module>
    merged_corpus.import_subview('train', splits['train'])
KeyError: 'train'

I am still unable to understand what this error is .. or why. 

Please if you can guide me to resolve this issue. 

Greetings.

**Comment by ynop** [comment]
Try to install the current development branch of audiomate.

**Comment by Tortoise17** [comment]
No such file or directory: '/home/data/common/clips/common_voice_de_17284684.mp3.mp3

why it is asking dual mp3 from common voice project? can you point out the issue where is with audiomate in input? or audioread has some problem with mp3 format. ?

**Comment by ynop** [comment]
Did you install audiomate from the master branch?

**Comment by Tortoise17** [comment]
Yes, I tried with PIP and with master branch both. Still I am facing this issue. I don't know why is it so.

**Comment by ynop** [comment]
This was an issue with the change to V2 of common-voice dataset.
But I fixed that one. There is no place I add an addtional mp3 extension.
https://github.com/ynop/audiomate/blob/master/audiomate/corpus/io/common_voice.py

Make sure you make a clean install (pip --upgrade) from the master.

**Comment by Tortoise17** [comment]
Sure, I think this should work now. !!!

may I ask you one more question. 

File "prepare_data.py", line 85, in <module>
    splits = splitter.split_by_length_of_utterances(
AttributeError: 'Splitter' object has no attribute 'split_by_length_of_utterances'

Why this is appearing ?

**Comment by ynop** [comment]
That API changed.
Just use one of the new methods (https://github.com/ynop/audiomate/blob/master/audiomate/corpus/subset/splitting.py)

I would use split_by_label_length. Audio duration takes a lot of time to just get the duration of all audiofiles.

**Comment by Tortoise17** [comment]
Thank you so much. I was thinking audio length. As I think there are 4 nice options available in your library. 

But I will try all for the test cases. 
and is it OK to use your script as public source license with the reference?

**Comment by ynop** [comment]
Yes, sure

**Comment by Tortoise17** [comment]
Dear Sir. 

I have one more question. 

While using only common voice data. 
after vocab preparation...!!! 

$>./data/kenlm/build/bin/lmplz --text data/clean_vocab.txt --arpa data/words.arpa --o 3
=== 1/5 Counting and sorting n-grams ===
Reading /home/deepspeech-german/data/clean_vocab.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 6382371 types 292380
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:3508560 2:18728366080 3:35115687936
/home/deepspeech-german/data/kenlm/lm/builder/adjust_counts.cc:60 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
ERROR: 2-gram discount out of range for adjusted count 3: -0.47422838
Aborted (core dumped)

this is a phase. Can you guide here what mistake is ? or reason of this error? maybe I am doing something wrong? Please help. 

Greetings.

**Comment by Tortoise17** [comment]
Dear Sir, 

One more question. !!

./run_training.sh: line 29: --train_batch_size: command not found

Do i need to change or remove something here? I think ..//

**Comment by Tortoise17** [comment]
Dear Sir, 

One question. 

Yet I am not able to train my own model. Because tensorflow 1.14 has some issues and nasty bugs. 
But for test case, I downloaded your model 

I run the command. 

deepspeech-german$> ../DeepSpeech/DeepSpeech.py --model data/lm/output_graph.pb --alphabet data/alphabet.txt --lm data/lm/lm.binary --trie data/lm/trie --audio output.wav

Command runs, but,
I am surprised, where is the output.txt gone which I am expecting as text from this wav file? can you please guide and help. 

Greetings.

**Comment by Tortoise17** [comment]
Dear Sir, 

Is it possible to use only common voice data for speech to text of German language? 
Please can you guide me the steps for training a model .. after downloading the data. 

I prepared the data, generated CSV with audiomate as you suggested, then word.arpa and lm.binary. But, afterwards, facing the errors. 

Maybe I am making some mistakes. specially while cleaning test. 
Please help. 

Below is the error. 

---------------------------------------------------------------------------------------------------------------------------------
deepspeech-german]$ ./run_training.sh $deepspeech $(realpath data/alphabet.txt) data/
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
W0903 14:04:25.496643 140376779990848 deprecation.py:323] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0903 14:04:25.608413 140376779990848 deprecation.py:323] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0903 14:04:25.608779 140376779990848 deprecation.py:323] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0903 14:04:25.609019 140376779990848 deprecation.py:323] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
WARNING:tensorflow:From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0903 14:04:53.760333 140376779990848 deprecation.py:506] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From DeepSpeech.py:231: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0903 14:04:55.000500 140376779990848 deprecation.py:323] From DeepSpeech.py:231: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
I Initializing variables...
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                       Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Header mismatch: Expected RIFF but found ID3#
	 [[{{node DecodeWav}}]]
	 [[tower_0/IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 894, in <module>
    tfv1.app.run(main)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/user/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 878, in main
    train()
  File "DeepSpeech.py", line 599, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech.py", line 567, in run_set
    feed_dict=feed_dict)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Header mismatch: Expected RIFF but found ID3#
	 [[{{node DecodeWav}}]]
	 [[tower_0/IteratorGetNext]]
./run_training.sh: line 51:  7943 Segmentation fault      (core dumped) $deepspeech_path/native_client/libctc_decoder_with_kenlm.so $alphabet_path $exp_path/lm.binary $exp_path/trie "$@"
(zs) [user@localhost deepspeech-german]$

**Comment by Tortoise17** [comment]
$> python3 prepare_data.py --cv data/common/ data
$> python3 prepare_vocab.py data/all.csv data/clean_vocab.txt
$> ./data/kenlm/build/bin/lmplz --text data/clean_vocab.txt --arpa data/word.arpa --o 3
$> ./data/kenlm/build/bin/build_binary -T -s data/word.arpa data/lm.binary
$> ./../DeepSpeech/native_client/generate_trie data/alphabet.txt data/lm.binary  data/trie
$> ./run_training.sh $deepspeech $(realpath data/alphabet.txt) data/


these are steps I used. Maybe the second step is faulty ??
I am using only common voice data. 

Please guide.

**Comment by ynop** [comment]
Can't say that easily.
From the above message there seems to be a problem with the audio format.

``` Expected RIFF but found ID3# ```

Check the deepspeech stuff, what they expect.

**Comment by Tortoise17** [comment]
You are so genius. 
The format is yet mp3 extension. Should it be wav?

**Comment by ynop** [comment]
I guess so (RIFF is the header of a wav file https://en.wikipedia.org/wiki/WAV).

The deepspeech-writer of audiomate does not handle that case.
You can either implement that in audiomate (https://github.com/ynop/audiomate/blob/master/audiomate/corpus/io/mozilla_deepspeech.py), by checking if it is already wav.

Or you do manually after exporting using audiomate.

**Comment by Tortoise17** [comment]
Perfect, 

yes you are right. additionally I have started shell script to work for formatting. I will update you about this until tomorrow as my experience says, this takes more than 6 hours to change format. 

Then I will ask for guide where stuck again until my first successful run. !!

**Comment by Tortoise17** [comment]
Dear Respected Sir,

May I ask you one question.
Normally, how much time it takes to train a model (any dataset) with your experience count.?
I have something like this position
Epoch 0 |   Training | Elapsed Time: 22:22:47 | Steps: 2378 | Loss: 137.282730

Can you guide and comment about it.? Or still I am maybe at some mistake.

Greetings.

**Comment by ynop** [comment]
Heavily depends on the amount of data and your hardware (gpus).

**Comment by Tortoise17** [comment]
Nice, thank you .. !!
and for common voice. can you have rough guess. ?
If CPUs are used.? how much they can demand. 
I have one machine 48 cores, one 24 cores.

**Comment by ynop** [comment]
Hmm, with an up-to-date gpu I would say a few days.
CPUs are normally too slow to train such things.
See for example: https://medium.com/@andriylazorenko/tensorflow-performance-test-cpu-vs-gpu-79fcd39170c

**Comment by Tortoise17** [comment]
I agree. They are super shit like 1/12 in performance .
So, up-to-date single GPU will be able to train in few days?like Titan.  or up to date 24 GPUs are required. This is important question.

**Comment by ynop** [comment]
With the scripts, as they are here, it took me a few days (about 3, cant remember exactly) with 3 or 4 titanXs. Including tuda/voxforge/swc data. Can't give you a more accurate guess.

**Comment by Tortoise17** [comment]
That is super great help. 
I can guess now. !! I will keep you updated with my progress.

**Comment by Tortoise17** [comment]
Dear Respected Sir, 

I would like to ask a question. Just as a test case, if I use your trained model, which version of deepspeech should I use to test your trained model? If you can guide. I tried over 0.5.1 and failed. while I searched for available info and maybe i missed somewhere. if you can guide. 

Greetings. 

Khawar

**Comment by Tortoise17** [comment]
Resolved
