### ISSUE TITLE
Kaldi data

### ISSUE THREAD

**Issue by Tortoise17** [ynop/deepspeech-german#13]
Dear Sir, 

good morning. I am trying to preprocess KALDI data for such training. I am failed with several tries. Can you guide me or is there any script to pre-process? or any link to get pre-processed data?

Greetings.

**Comment by ynop** [comment]
Basically the same way as with the other data (just use the KaldiReader reader="kaldi").
But since kaldi format allows a lot of different file-definitions, not everything is supported.

Just post an excerpt of your wav.scp, then I can say if it should work.

**Comment by Tortoise17** [comment]
That is what I am failed. How to get in wav.scp format. 
Also, one question. Have you tried m-ailab data? I got lot of errors and infinite loss while using that data. and without that, things seems to be better.

**Comment by ynop** [comment]
No haven't tried mailabs for deepspeech.
I don't get what you want.
Can you explain exactly what you are trying to do?

**Comment by Tortoise17** [comment]
Actually, I am trying to train a model with Kaldi. and here I am missing kaldi proper format for input of pre-processing.

**Comment by ynop** [comment]
You can use something like this to save in kaldi format.
```
from audiomate.corpus import io

os.makedirs('out/path', exist_ok=True)
writer = io.KaldiWriter()
writer.save(corpus, 'output/esc_subview')
```

docs: https://audiomate.readthedocs.io/en/latest/reference/io.html#kaldi

**Comment by Tortoise17** [comment]
Thank you so much. I will try this and will tell you. Thank you again.

**Comment by Tortoise17** [comment]
Resolved
