### ISSUE TITLE
voxforge data download

### ISSUE THREAD

**Issue by Tortoise17** [ynop/deepspeech-german#15]
Dear friend. 

I want to ask that do you have script for voxforge data download and preprocess ?If you can share. !!

**Comment by ynop** [comment]
Yes, you can do that with audiomate (https://github.com/ynop/audiomate).
Take a look at https://github.com/german-asr/megs. There I have scripts, which preprocess german datasets (including voxforge) using audiomate.

**Comment by Tortoise17** [comment]
That is great. and download as well? because I cannot find the way to download the dataset.

**Comment by Tortoise17** [comment]
Great I got it. Now I will test and will tell if find any problem. Thank you so much. Great help.

**Comment by Tortoise17** [comment]
Still. The download issue. ! I have all datasets but voxforge downloading is confusing me. Can you share the link which script downloads it?

**Comment by ynop** [comment]
https://github.com/german-asr/megs/blob/4d98b3d61048a23f29a431b13565c6b8dd1091d1/scripts/download.py#L27-L35

**Comment by Tortoise17** [comment]
exactly. I tried it with command below 

python download.py data_path/

but it didn't work.

**Comment by DebVortex** [comment]
Sorry for me as "bystander" dropping in, but @Tortoise17 could you be more specific what exactly is not working? I downloaded and installed the script and it seems to run on my end. What exact message do you get?

**Comment by Tortoise17** [comment]
> Sorry for me as "bystander" dropping in, but @Tortoise17 could you be more specific what exactly is not working? I downloaded and installed the script and it seems to run on my end. What exact message do you get?

python3 scripts/download.py data/
You have to download common-voice de corpus manually to data/download/common_voice! 
this message is even if I have put the common voice data in the folder. 

while. I am focused at the moment with voxforge tuda common voice and mailab combined. 
am I making any mistake? or ?

**Comment by DebVortex** [comment]
@Tortoise17 try running `mkdir -p data/download/common_voice` first and then your `python3 scripts/download.py data/download/`. Once the `common_voice` folder exists, you do not get the message above and the download for the others should start.

**Comment by Tortoise17** [comment]
Great. !! although there is error with number of workers. But I excluded out that. and your this command above stated helped in download start. Thank you so much. I will ask for little more once I complete download. Great help. Thank you . !!

**Comment by Tortoise17** [comment]
It worked for voxforge (thank you). But TUDA and SWC has issues with audiomate. Have you success with that or ? I have pointed out that at the original issue page. !!
